27  vi inventory.ini
   28  chmod 600
   29  chmod 600 /tmp/ec2.key
   30  nsible -i inventory.ini all -m ping
   31  ansible -i inventory.ini all -m ping
   32  vi inventory.ini
   33  ansible -i inventory.ini all -m ping
   34  vi inventory.ini
   35  ansible -i inventory.ini all -m ping
   36  sudo journalctl -k | grep -i oom
   37 # Check kernel messages for OOM killer activity
   38  dmesg -T | grep -i oom
       sudo journalctl -k | grep -i oom

       # Try fixing the issue by adding swap space
       
   39  sudo fallocate -l 2G /swapfile
   40  sudo chmod 600 /swapfile
   41  sudo mkswap /swapfile
   42  sudo swapon /swapfile

   # Tried pining again after adding swap space

   43  ansible -i inventory.ini all -m ping
   44  ansible -i inventory.ini all -m ping -f 2

   # Tried Force Python to use mitogen or set the Ansible fork method environment variable before running:
  
   45  export ANSIBLE_FORKS=5
   46  export PYTHONWARNINGS="ignore"

   # Then run the ping command again by debugging with verbose output:

   47  ansible -i inventory.ini all -m ping -vvv
    
   49  sudo apt install ansible-core -y
   50  sudo apt upgrade ansible
   51  cd ~/ansible_test
   52  ansible -i inventory.ini all -m ping -vvv
   53  ansible -i inventory.ini all -m ping
   54  vi inventory.ini

   # To see if the Linux kernel is killing the process:
   55  sudo dmesg -T | tail -n 30

   # I tried running the ping command again with Python3 and Ansible module:
   56  python3 -m ansible -i inventory.ini all -m ping
   
   # Check if AppArmor is restricting Ansible or its subprocesses:
   
   57  sudo aa-status

   # If AppArmor is enabled, try putting the Ansible process into complain mode or disabling the profile for the Ansible binary:
   # Put the who AppArmor Profile into Complain Mode (Recommended)
   # This keeps AppArmor active while preventing it from killing who:
   58  sudo aa-complain /usr/bin/who

   # Try installing the AppArmor utilities and disabling the profile for the Ansible binary:
   60  sudo apt install apparmor-utils -y
   61  ansible -i inventory.ini all -m ping

   # Try stopping AppArmor completely (Not Recommended for Production Systems):

   62  sudo systemctl stop apparmor
   63  ansible -i inventory.ini all -m ping
   64  sudo aa-disable /etc/apparmor.d/who
   65  # OR
   66  sudo aa-disable /etc/apparmor.d/usr.bin.who
   67  ansible -i inventory.ini all -m ping

   # Run this command with Python's crash-trace flags enabled to see if it provides more information about the crash:
   68  PYTHONFAULTHANDLER=1 ANSIBLE_DEBUG=1 ansible -i inventory.ini all -m ping -vvvv
   
   # Bypass Multiprocessing Forks (ANSIBLE_FORKS=1)
   # Force Ansible to execute in a single serial process rather than spawning worker threads:

   71  ANSIBLE_PIPELINING=True ansible -i inventory.ini all -m ping
   
   72  vi inventory.ini
   73  ansible -i inventory.ini all -m ping
   
   # The strng were formated as a single line, so I tried to format it as a multi-line string in the inventory file:

   [nginx]
54.167.94.142 ansible_user=ubuntu ansible_ssh_private_key_file=/tmp/ec2.key ansible_ssh_common_args='-o StrictHostKeyChecking=no'

# Then I tried running the ping command again:

   74  ansible -i inventory.ini all -m ping